@startuml

scale 2
left to right direction
rectangle main
rectangle CAN
rectangle TCM
rectangle ECM

ECM -> TCM : RPM
main -> ECM : acc ped
TCM -> ECM : gear

start
while(blaha)
if(RPM > lim) then(yes): change gear;


actor driver

@enduml